commands:
  - command:
    input: Que horas são?
    entity: time
    action: getTime
  - command:
    input: Que dia é hoje?
    entity: date
    action: getDate
  - command:
    input: Pesquisar no google qual a
    entity: search
    action: getAnswer
  - command:
    input: Qual a temperatura atual?
    entity: weather
    action: getWeather